# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
REPOSITORY_CHECKOV_DISABLE_ERRORS: true
GIT_GIT_DIFF_DISABLE_ERRORS: true
YAML_YAMLLINT_DISABLE_ERRORS: true
ACTION_ACTIONLINT_DISABLE_ERRORS: true
REPOSITORY_GIT_DIFF_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS:
- "**/*.md"
