name: Bloat

on:
  pull_request:
  #   types: [opened]
  # issue_comment:
  #   types: [created, edited, deleted]

permissions:
  pull-requests: write

jobs:
  cargo_bloat:
    # if: contains(github.event.comment.body, '/bloat')    # check if the comments come from pull request, exclude those from issue.
    name: Cargo Bloat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-bloat
        run: cargo install cargo-bloat
      - name: Run cargo bloat
        run: |
          echo "# Bloat report" > ./bloat.txt &&\
          cargo bloat --release >> ./bloat.txt
      - name: Post results to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          header: Bloat Report
          path: ./bloat.txt
