name: Deploy
on:
    workflow_run: # Is Only Triggered on the main Branch
        workflows: ["Tests"]
        types:
          - completed
jobs:
    release:
      name: Publish
      runs-on: ubuntu-latest
      if: github.event.workflow_run.conclusion == 'success' && github.ref_type == 'tag'
      timeout-minutes: 10
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        run: |
          echo "Publishing"
     