name: Deploy
on:
    workflow_run:
        workflows: ["Tests"]
        types:
          - completed
jobs:
    release:
      name: Publish
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/v') && github.event.workflow_run.conclusion == 'success'
      timeout-minutes: 10
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        run: |
          echo "Publishing"